- README.md
- adapter/database.go
- adapter/mysql/mysql.go
- adapter/postgres/postgres.go
- cmd/mysqldef/mysqldef.go
- cmd/psqldef/psqldef.go
I want to use unix domain socket. 
I implemented that supports.
- mysqldef
- `-S | --socket` option added  ( like `mysql -S /tmp/mysql.sock` )
- psqldef
- `-h, --host` option modifyed ( hostname or directory )
> Supporting unix domain socket

- cmd/mysqldef/mysqldef_test.go
- schema/ast.go
- schema/generator.go
- schema/parser.go
> supporting enum values

- cmd/psqldef/psqldef_test.go
Refs: https://github.com/k0kubun/sqldef/issues/35
Update TestPsqldefDataTypes TODO comment.
cc @kei2100
> Update TestPsqldefDataTypes TODO comment

- cmd/mysqldef/mysqldef_test.go
- schema/generator.go
refs: #68
I fix this very naively but it is great if there are more smart ways
> Fix charset and not null order on MySQL

- Makefile
- cmd/mysqldef/mysqldef.go
- cmd/psqldef/psqldef.go
- cmd/sqlite3def/sqlite3def.go
Embed the result of `git describe --tags --abbrev=0` in ldflags.
Fixes #89.
> Add `--version` option

- .github/workflows/sqldef.yml
- Dockerfile
- Makefile
- docker-compose.yml
- go.mod
darwin/386 is no longer supported since go1.15.
https://github.com/golang/go/issues/37610
> Update to go1.16 and drop darwin/386 support

- cmd/psqldef/psqldef_test.go
- schema/generator.go
This is supporting changing default  for postgres.
> Support changing default

- adapter/mssql/mssql.go
- cmd/mssqldef/mssqldef_test.go
- schema/generator.go
This change supports the following features.
- ADD FOREIGN KEY
- DROP FOREIGN KEY
> mssqldef: support foreign key

- cmd/mssqldef/mssqldef_test.go
- cmd/mysqldef/mysqldef_test.go
- schema/generator.go
This change supports the following features.
- ADD INDEX
- DROP INDEX
> mssqldef: support index

- adapter/database.go
- cmd/psqldef/psqldef.go
- cmd/psqldef/psqldef_test.go
- sqldef.go
Closes #192 
This PR adds `--before-apply` option to psqldef as discussed in #192.
> Add `--before-apply` to psqldef

- cmd/mysqldef/mysqldef.go
- cmd/mysqldef/mysqldef_test.go
Close https://github.com/k0kubun/sqldef/issues/215
Related PR: https://github.com/k0kubun/sqldef/pull/195
> Add `--before-apply` to mysqldef

- adapter/postgres/postgres.go
In Postgresql, identifiers must be enclosed in "" if they are mixed case.
When exporting with psqldef, some identifiers were not enclosed with "".
Input SQL
```
CREATE TYPE "enumType" AS ENUM ('A', 'B', 'C');
CREATE TABLE "tableA" (
id bigint NOT NULL,
name text
);
CREATE UNIQUE INDEX uindex ON "tableB" USING btree ("tableA_id");
CREATE TABLE "tableB" (
id bigint NOT NULL,
"tableA_id" bigint NOT NULL,
name text,
enum "enumType"
);
ALTER TABLE ONLY "tableA" ADD CONSTRAINT "fk_tableA" FOREIGN KEY (id) REFERENCES "tableB"("tableA_id") ON UPDATE CASCADE ON DELETE CASCADE;
```
Current output
```
CREATE TYPE enumType AS ENUM ('C', 'B', 'A');
CREATE TABLE public.tableB (
"id" bigint NOT NULL,
"tableA_id" bigint NOT NULL,
"name" text,
"enum" "enumType"
);
CREATE UNIQUE INDEX uindex ON …
```
> quote identifer

- README.md
- cmd/mysqldef/mysqldef.go
- cmd/mysqldef/mysqldef_test.go
- cmd/testutils/testutils.go
- schema/generator.go
- sqldef.go
Feature to skip specific tables.
Manage it in a file and skip it. (Regexp are also available)
Provided by CLI. 
Previous discussion
https://github.com/k0kubun/sqldef/pull/221
```
--skip-file                Skip file-managed specified tables
```
> feat: Support for skipping tables

- cmd/psqldef/tests.yml
- database/postgres/database.go
- schema/generator.go
> [psqldef] Support changing precision and scale of numeric type

- cmd/psqldef/tests.yml
- database/postgres/database.go
> [psqldef]Support export of composite foreign key constraint

- cmd/mysqldef/tests.yml
- schema/generator.go
> [mysqldef] fix for change primary keys got error from mysql migration if any key has AUTO_INCREMENT

- README.md
- cmd/psqldef/psqldef.go
- cmd/psqldef/psqldef_test.go
hi.
Add --config option to allow psqldef to filter target tables
> [psqldef] Add --config option in psqldef

- cmd/psqldef/psqldef_test.go
- schema/generator.go
> Filter primary key, foreign key and index in target_tables of --config option 

- go.mod
- go.sum
Close https://github.com/k0kubun/sqldef/issues/299
> Upgrade pg_query_go to 2.2.0

- cmd/mysqldef/mysqldef.go
- cmd/mysqldef/mysqldef_test.go
- cmd/psqldef/psqldef.go
- cmd/psqldef/psqldef_test.go
- database/database.go
- schema/generator.go
> Add skip_tables option to config yaml

- parser/ast.go
- parser/parser.go
- parser/parser.y
- schema/ast.go
- schema/parser.go
> sqlite3def: Remove unused variables

- cmd/mssqldef/mssqldef_test.go
- cmd/mysqldef/mysqldef_test.go
- cmd/psqldef/psqldef_test.go
- cmd/sqlite3def/sqlite3def_test.go
- cmd/testutils/testutils.go
* Replace "\r\n" with "\n" in command output on test.
> Support tests on windows.

- .github/ISSUE_TEMPLATE.md
> Modify issue_template.md

- cmd/mssqldef/mssqldef_test.go
- cmd/mssqldef/tests.yml
- cmd/psqldef/psqldef_test.go
- cmd/psqldef/tests.yml
- cmd/testutils/testutils.go
- database/database.go
- database/file/database.go
- database/mssql/database.go
- database/mysql/database.go
- database/postgres/database.go
- database/sqlite3/database.go
- schema/generator.go
- schema/parser.go
- sqldef.go
Support non deault schema on PostgresSQL and SQL Server.
* Add DefaultSchema method to database.Database interface.
* Add parameter named defaultSchema to some functions/methods.
* Apply some procedures related to schema to MSSQL.
* Add test cases for PostgreSQL and SQL Server.
> Support non standard defaut schema.

- cmd/psqldef/tests.yml
- schema/generator.go
fix https://github.com/k0kubun/sqldef/issues/375
> [psqldef] support for changing timezone in time/timestamp column

- cmd/psqldef/psqldef_test.go
- database/postgres/database.go
> psqldef: do not export extension dependent objects.

- cmd/psqldef/tests.yml
- schema/generator.go
I fixed an issue where the difference was not output when the comment was changed.
> Support for update comment

- database/postgres/parser.go
- database/postgres/tests.yml
- go.mod
- go.sum
I have updated pgquery to the latest v4.2.0. The changelog is as follows:
- Update to libpg_query 15-4.2.0
- Update to PostgreSQL 15.1
https://github.com/pganalyze/pg_query_go/blob/main/CHANGELOG.md
> Update pgquery versiont to v4.2.0

- cmd/psqldef/tests.yml
- database/postgres/parser.go
- database/postgres/tests.yml
fix: https://github.com/k0kubun/sqldef/issues/396
> Fix error when view definition has no from clause

- cmd/psqldef/tests.yml
- schema/generator.go
Fix #415
Thank you for the advice. I send a pull request.
> [psqldef] Fix dupricate `WITH TIME ZONE`

- cmd/mssqldef/tests.yml
- database/mssql/database.go
> mssqldef: Quote constraint name

- database/mssql/database.go
Currently, mssqldef executes 4 queries for each table exists in database to get schema information.
If there are many tables in database, this process takes a long time.
This PR reduces the number of queries executing.
Benchmark results are bellow.
There are 500 tables in database, and each test is run after mssql service is restarted.
v0.16.3
```
$ time ./mssqldef -U sa -P Passw0rd mssqldef_test --export > /dev/null
real    0m28.817s
user    0m0.906s
sys     0m0.285s
```
After applying the PR.
```
$ time ./mssqldef -U sa -P Passw0rd mssqldef_test --export > /dev/null 
real    0m1.151s
user    0m0.593s
sys     0m0.076s
```
> mssqldef: Improve performance.

- database/postgres/database.go
> [psqldef] getForeignDefs SQL Tuning

- CHANGELOG.md
I created a Pull Request to update CHANGELOG because I don't have permission to push to the master branch.
```
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: 10 of 10 required status checks are expected.
To github.com:k0kubun/sqldef.git
! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'github.com:k0kubun/sqldef.git'
```
> Version 0.16.11

- README.md
- cmd/psqldef/psqldef.go
- cmd/psqldef/psqldef_test.go
- database/database.go
- database/postgres/database.go
Ref. https://github.com/sqldef/sqldef/issues/466 and https://github.com/sqldef/sqldef/pull/467
I have added target_schema config in order to apply specific PostgreSQL schema's tables.
@k0kubun Thanks for replying the issue and prev PR. Please review.
> [psqldef] Add target_schema config

- README.md
- cmd/mssqldef/mssqldef.go
- cmd/mysqldef/mysqldef.go
- cmd/psqldef/psqldef.go
- cmd/sqlite3def/sqlite3def.go
Improve the help message about diff two files #484
> docs: improve the help message about diff two files

- cmd/psqldef/tests.yml
- schema/generator.go
fix https://github.com/sqldef/sqldef/issues/405
@k0kubun The impact is significant, so I would appreciate your review.
> Put the alter foreign key and index at the end of DDLs

- cmd/testutils/testutils.go
- database/database.go
- database/mssql/parser_test.go
- database/postgres/parser_test.go
- go.mod
- go.sum
upgrade https://pkg.go.dev/gopkg.in/yaml from v2 to v3.
> upgrade gopkg.in/yaml.v3

- cmd/mssqldef/mssqldef_test.go
- cmd/testutils/testutils.go
- parser/node.go
> Fix trivial typos

- cmd/psqldef/tests.yml
- schema/ast.go
- schema/generator.go
- schema/parser.go
fix https://github.com/sqldef/sqldef/issues/488
> [psqldef] Fix the error when deleting columns from view

- database/mssql/database.go
- schema/generator.go
Support "ALTER COLUMN" to change the column size.
Also support precision for numeric and decimal to pass test, as a result #445 is resolved.
> mssqldef: Support ALTER COLUMN

- cmd/psqldef/tests.yml
- database/postgres/database.go
- database/postgres/parser.go
- database/postgres/tests.yml
- parser/node.go
- schema/ast.go
- schema/generator.go
- schema/parser.go
This is a continuation of the implementation from https://github.com/sqldef/sqldef/pull/528.
FYI @sanemat
fix https://github.com/sqldef/sqldef/issues/473
fix https://github.com/sqldef/sqldef/pull/528
> [psqldef] support exclusion constraints

- cmd/psqldef/psqldef_test.go
- database/postgres/database.go
- schema/generator.go
> [psqldef] Change the pkey using constraints

- cmd/mssqldef/tests.yml
- database/mssql/database.go
> mssqldef: Fix parsing VIEW with header comment

- cmd/mysqldef/tests.yml
- schema/generator.go
> mysqldef: Fixed an issue where removing table comments caused an error.

- CHANGELOG.md
@sqldef/sqldef 
ref https://github.com/sqldef/sqldef/discussions/649
Hi all,
Normally, a Pull Request is not required for a release, but since this is a momentous occasion for our first major version release, I thought we should celebrate together and created a Pull Request. Let's appreciate everyone's efforts so far! Thank you!
> Release v1

- README.md
- cmd/mssqldef/mssqldef_test.go
> mssqldef: Add test code for config & config-inline

- .github/workflows/tagpr.yml
Until setting up create-github-app-token successfully.
> disable tagpr for now (only triggered by hand)

- .github/workflows/tagpr.yml
Still not settled :(
Reverts sqldef/sqldef#749
> Revert "Enable push event for master branch in tagpr workflow"

- README.md
Example for release pull-requests: https://github.com/sqldef/sqldef/pull/757
FYI: @k0kubun @knaka @odz @hokaccha
> update "Release" section: all the maintainers do is to merge release pull requests created by tagpr

- .github/workflows/sqldef.yml
- Makefile
To make sure `parser/parser.go` is fresh & clean.
> [CI] add parser-integrity job

- cmd/testutils/testutils.go
- database/database.go
- database/dry_run.go
- database/file/database.go
- database/mssql/database.go
- database/mysql/database.go
- database/postgres/database.go
- database/sqlite3/database.go
- sqldef.go
Since `--export` is the feature name for that.
> refactoring: dump -> export for internal functions that implement --export
