sqldef/sqldef

adapter/postgres/postgres.go

`GRANT` and `REVOKE` sql statements produced by pg_dump were not being correctly parsed.
I don't think sqldef is intended to manage permissions so rather than attempt to alter the parser to correctly parse them I have added them to the list of statements that are removed from the pg_dump output.
The error I was getting before this change was `syntax error at position 7 near 'revoke'`.

Remove REVOKE and GRANT statements from dumped SQL

---

README.md
cmd/mysqldef/mysqldef.go
cmd/psqldef/psqldef.go

I do not want to record password in history or environment.
I implemented using prompt. 
Add `--password-prompt` option to mysqldef and psqldef command
I understand native option of mysql or pg_dump, psql command.
But go-flags does not allow empty value. ( Is wrong? )

password from prompt

---

cmd/mysqldef/mysqldef_test.go
schema/ast.go
schema/generator.go
schema/parser.go

MySQL "ON UPDATE CURRENT_TIMESTAMP"  support.
"ON UPDATE" is already parsed. 
https://github.com/k0kubun/sqldef/blob/6ae81394adbb0b2d854237e7a9e2db0f08835fac/sqlparser/parser.y#L720
I know that "defaultVal, length, scale" vales are difficult to compare.
But  "ON UPDATE" value is easy to compare.

MySQL timestamp initialization "ON UPDATE CURRENT_TIMESTAMP"

---

cmd/mysqldef/mysqldef_test.go
schema/ast.go
schema/generator.go
schema/parser.go

This PL emits `alter ... after...` even if only the order of the columns is different.

Fix column order.

---

sqldef.go

Currently `sqldef.readFile` function removes line ending characters when input from stdin.
DDL is almost valid even if their lines are combined, but line-sensitive syntax (e.g. `-- line comments`) is broken.
Here is an example schema, including simple table definition written in multiline.
```
CREATE TABLE `sample` (
`id` INT -- ID
);
```
`--file` option works well because it preserves line endings.
```
% mysqldef -uroot example --dry-run --file sample.sql 
-- dry run --
CREATE TABLE `sample` (
`id` INT -- ID
);
```
However stdin is not working.
```
% mysqldef -uroot example --dry-run < sample.sql
found syntax error when parsing DDL "CREATE TABLE `sample` (  `id` INT -- ID)": syntax error at position 41
```
Given lines are combined, and `-- ID` is no longer valid line comment.
I tested …

Fix to preserve line feeds when using stdin

---

adapter/postgres/postgres.go

#29 
before
```
2019/08/14 17:28:33 Error on DumpDDLs: exit status 1
```
after
```
2019/08/14 17:28:33 Error on DumpDDLs: exit status 1 :
pg_dump: server version: 10.1; pg_dump version: 9.6.15
pg_dump: aborting because of server version mismatch
```

Make error outputs more detail to show pg_dump errors

---

adapter/postgres/postgres.go

I checked `Drop pg_dump dependency` issue. https://github.com/k0kubun/sqldef/issues/10.
Easy to implement `Drop pg_dump dependency` and `Support SERIAL` together.
@k0kubun 
Please check my plan is correct.
- Support SERIAL -> I will fix other PR(this PR is `Drop pg_dump dependenc` only)

Remove pg_dump dependency

---

adapter/postgres/postgres.go
cmd/psqldef/psqldef_test.go

In the current implementation not support this schema
```sql
id bigint NOT NULL,
name text,
created_at timestamp
);
```
This PR is supported `timestamp` only.
Not support `timestamp without tz` and `timestamp with tz`

Support timestamp (without tz) on psqldef

---

adapter/postgres/postgres.go
cmd/psqldef/psqldef_test.go

If applied, this commit will fix #35

Fix output length when `psqldef --export`

---

README.md
adapter/database.go
cmd/mysqldef/mysqldef.go
cmd/mysqldef/mysqldef_test.go
cmd/psqldef/psqldef.go
cmd/psqldef/psqldef_test.go
sqldef.go

issue: https://github.com/k0kubun/sqldef/issues/43
I implemented the `--skip-drop` option as one way to avoid destructive changes.
Please consider it.

[Proposal] Add --skip-drop option

---

schema/generator.go

sqldef fails on change column definitions from implicit NULL to NOT NULL.
sqldef version: v0.7.6
```sql
ALTER TABLE sample CHANGE COLUMN name name varchar(255) NOT NULL
```
```sql
CREATE TABLE sample (
name varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
```
```sql
CREATE TABLE sample (
name varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
```
```
$ cat test.sql 
CREATE TABLE sample (
name varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
$ mysqldef -uroot dev < test.sql 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5b14a9]
goroutine 1 [running]:
github.com/k0kubun/sqldef/schema.(*Generator).haveSameColumnDefinition(0xc000159cc0, 0xc00011e21c, 0x4, 0x0, …
```

Fix segmentation violation

---

cmd/mysqldef/mysqldef_test.go
cmd/psqldef/psqldef_test.go
cmd/sqlite3def/sqlite3def_test.go
sqlparser/dependency/hack/hack_test.go

When the test is in error, the number of lines of the test helper is output as shown below.
```
sqlite3def_test.go:212: failed to execute 'sqlite3def sqlite3def_test --file schema.sql' (error: 'exit status 1'): `found syntax error when parsing DDL "CREATE VIEW `view_users` AS select id from users where age = 1": syntax error at position 14 near '`'
```
This makes it difficult to investigate errors, so use `t.Helper()` to display the number of lines called.
https://golang.org/pkg/testing/#T.Helper

Add `t.Helper()`

---

cmd/mysqldef/mysqldef_test.go
cmd/psqldef/psqldef_test.go
cmd/sqlite3def/sqlite3def_test.go
schema/generator.go
sqlparser/token.go

If the identifier is not escaped, an error will occur when handling the same table name or column name as the reserved word.
So I added a process to escape the identifier.
ref.
https://github.com/k0kubun/sqldef/commit/7e4a2dd53116551e9cb1d7e57f5d13a962c08e89

Add identifier escaping process

---

Makefile

Apple Silicon is supported in 1.16.
https://golang.org/doc/go1.16#darwin

Support darwin/arm64

---

README.md
cmd/psqldef/psqldef.go

I don't know if it's intentional implements that supporting `PGPASS` environment variable to set password on psqldef
The psql command used `PGPASSWORD` environment variable.
https://www.postgresql.org/docs/current/libpq-envars.html
> PGPASSWORD behaves the same as the password connection parameter. 
Should I support `PGPASS` for backward compatibility?

fix postgres environment variable

---

cmd/mssqldef/mssqldef_test.go
schema/ast.go
schema/generator.go
schema/parser.go

This change supports the following features in sql server.
- ADD PRIMARY KEY
- DROP PRIMARY KEY

mssqldef: support PRIMARY KEY

---

adapter/postgres/postgres.go

Fixed the error on the DSN contains symbols.
```bash
$ export PGPASSWORD=".:?-&/%="
$ psqldef -U "user_.:?-&/%=" sandbox_db --skip-drop --file=test.sql
2021/07/02 16:26:34 Error on DumpDDLs: dial tcp: lookup user_.: no such host
```
https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNECT-SSLROOTCERT
I believe both of them are useful in case of AWS IAM Database Authentication. 🚀

psqldef: Escape DSN parts & Add PGSSLROOTCERT support

---

README.md

It looks like this repository is no longer using Travis CI.
So I migrated.

Migrate to GitHub Actions badge

---

cmd/mysqldef/mysqldef_test.go
schema/ast.go
schema/generator.go
schema/parser.go

I want to add column with it's comment, so I suggest to add `COMMENT '...'` after `ON UPDATE` keyword.
I usually use only mysql, so if additional patch is needed, let me know anytime. :)
p.s. Thank you for maintaining this tool. I am using it to maintain our db schema as code like IaC.

Support column comment

---

adapter/mysql/mysql.go

I added an extra where clause to specify view definition for mysqldef
- We have view with the same name with different database.
- Thus, I added the where clause to specify the view.

enable to get definition of view with same name, other database for mysql

---

adapter/database.go
adapter/file/file.go
cmd/mssqldef/mssqldef.go
cmd/mysqldef/mysqldef.go
cmd/mysqldef/mysqldef_test.go
cmd/psqldef/psqldef.go
cmd/sqlite3def/sqlite3def.go
sqldef.go

```
$ cat before.sql
id bigint PRIMARY KEY NOT NULL,
created_at datetime NOT NULL
);
$ cat after.sql
id bigint PRIMARY KEY NOT NULL,
name varchar(40) DEFAULT NULL,
created_at datetime NOT NULL
);
$ mysqldef --file before.sql --file after.sql
-- dry run --
ALTER TABLE `users` ADD COLUMN `name` varchar(40) DEFAULT null AFTER `id`;
```

Support comparing --file options

---

schema/parser.go

This patch was written in favor of boyscout rule.
related comment: https://github.com/yuku/sqldef/commit/833f289f95d63005bcf87ca394ae7007b2f963e8#commitcomment-64216606

Prefer referencing consts over using string literals

---

adapter/postgres/postgres.go
cmd/psqldef/psqldef_test.go

By v0.11.23, psqldef cannot handle DDL like this:
```sql
CREATE TABLE test.users (id serial primary key);
--           ^^^^^
```
This PR fixes the issue.
This PR also
* refactors psqldef_test.go a bit:
* Define the name of test database as constant variable and reuse it in favor of DRY.
* Hide the detail of how SQLs are submitted to a Postgres server from each test case.
* fixes typo: foregin → foreign

Fix bug that psqldef cannot handle CREATE TABLE with schema

---

.github/workflows/sqldef.yml
docker-compose.yml

https://github.com/k0kubun/sqldef/pull/188#issuecomment-1019416908
This PR also updates the default postgres version used in development from 12 to 14.

Add postgres 13 and 14 to CI test matrix

---

adapter/postgres/postgres.go
cmd/psqldef/psqldef_test.go

Suppose there are two tables having:
* same table name
* same primary key column name
```sql
-- e.g.
create table user.accounts (id int primary key);
create table bank.accounts (id int primary key);
```
psqldef generates following DDL every time:
```sql
-- Apply --
ALTER TABLE "user"."accounts" DROP CONSTRAINT "accounts_pkey";
ALTER TABLE "user"."accounts" ADD primary key ("id");
ALTER TABLE "bank"."accounts" DROP CONSTRAINT "accounts_pkey";
ALTER TABLE "bank"."accounts" ADD primary key ("id");
```
This PR fixes this issue.

Fix bug that psqldef attempts to drop&add pk every time if two tables have same name and pk

---

Makefile
cmd/mysqldef/mysqldef_test.go
cmd/psqldef/psqldef_test.go

By this change, we can run a test case easily from editor (VSCode in my case).
In addition, the ability to inject envvar has been added, increasing the flexibility of testing.

Make it easy to run a single test case

---

adapter/postgres/postgres.go
cmd/psqldef/psqldef_test.go

Suppose there are two similar tables in two schemas:
```sql
create table user.accounts (id int);
create table bank.accounts (id int);
```
If we drop a column from a table:
```sql
create table user.accounts (id int);
create table bank.accounts ();
```
`psqldef` generates duplicated `drop column`:
```
-- Apply --
ALTER TABLE "bank"."accounts" DROP COLUMN "id";
ALTER TABLE "bank"."accounts" DROP COLUMN "id";
```
This PR fixes the issue.

Enable to drop a column even if there is similar column in other schema

---

adapter/postgres/postgres.go
cmd/psqldef/psqldef_test.go

Fixes the bug I mentioned in https://github.com/k0kubun/sqldef/pull/196#issuecomment-1024840782
> * Bug fixes
>   * (high priority): `alter table non_public.foo add constraint uniq unique (col);` always generate `DROP INDEX uniq;` and it causes `pg: index "uniq" does not exist.`
>     * why high?: the table storing slack installation JSON lives in non public schema.
This PR also includes two chore commits:
1. c693d02031234f590f6ccd26b04f261f0ac7e805 While addressing the issue, I needed to check the result of `--export` many times, so I added `assertExportOutput()` helper and refactored psqldef_test.go a bit.
2. 31542f5661b80b6585bebdde266cb5109ab90d72 When I tested the `assertExportOutput()`, I found a bug in the test case added by #196
* It was a test of a situation that rarely happens, …

Enable to add a unique constraint to tables in non-public schema

---

README.md
cmd/mssqldef/mssqldef_test.go
cmd/mssqldef/tests/create_table.yml
cmd/mysqldef/mysqldef_test.go
cmd/mysqldef/tests/create_table.yml
cmd/psqldef/psqldef_test.go
cmd/psqldef/tests/create_table.yml
cmd/sqlite3def/sqlite3def_test.go
cmd/sqlite3def/tests/create_table.yml
cmd/testutils/testutils.go
go.mod
go.sum
sqldef.go

* Address difficulty of writing sqldef tests in Go
* Using `"` vs <code>`</code> for escaping identifiers while both are also needed for Go string literal
* Tabs and spaces in indentation
* Accelerate test execution by not invoking sqldef commands every time
* Migrating existing tests to the framework is to be done in other commits
* mysqldef tests also reuse the same DB connection for all tests
* Eliminate repetition of test codes
* e.g. `resetTestDatabase`, `nothingModified` for the second apply

Introduce a YAML-based test framework

---

database/postgres/postgres.go

`information_schema.tables` is reordered each time the schema is changed, so there is a problem that the difference in the exported schema is large.
To solve this problem, I fixed the order by specifying order by.

Sort tableNames by table_name

---

cmd/mysqldef/mysqldef.go
cmd/mysqldef/mysqldef_test.go
cmd/psqldef/psqldef_test.go
cmd/testutils/testutils.go
database/database.go
schema/generator.go
sqldef.go

Close https://github.com/k0kubun/sqldef/issues/246
With a YAML file like below, you can specify tables that sqldef should manage.
```yml
target_tables: |
users
users_\d+
```
You can specify the config file like `mysqldef --config sqldef.yml`.

Implement --config option

---

.github/workflows/sqldef.yml
Makefile

Fix https://github.com/k0kubun/sqldef/issues/270
There are some challenges in cross-compiling cgo programs for darwin with `zig cc` https://github.com/ziglang/zig/issues/9050#issuecomment-859939664. While they gave a solution to the mentioned problems, even if we use all of them for sqldef, darwin binaries result in a segmentation fault on `runtime.cgocall` like #270.
This implementation is based on https://github.com/itamae-kitchen/mitamae/pull/105. I confirmed that both amd64 and arm64 binaries generated by it don't cause a segmentation fault when it calls the cgo path, unlike the ones generated by `zig cc`. So I'm switching to `zig cc` for darwin builds.

Cross-compile darwin targets with osxcross

---

cmd/mysqldef/tests.yml
schema/generator.go

https://github.com/k0kubun/sqldef/issues/49 has been resolved, but not yet when default value is specified.
The specific problem is that it would output meaningless diffs in situations like the test case I added.
The problem was because MySQL treats BOOLEAN values as INT internally, but we were not handling them as such.
see: https://dev.mysql.com/doc/refman/8.0/en/boolean-literals.html
This PR fixes these problems.

[mysqldef] Fix handling default values of "boolean" correctly.

---

cmd/mysqldef/mysqldef.go
database/database.go
database/mysql/database.go

When I tried to connect Aurora MySQL 1.x, but mysqldef does not work.
( note : Windows 10 21H2 19044.1889, mysqldef: v0.13.7, mysql cli:  v8.0.30 )
```
>mysqldef -u username -h localhost --export dbname
2022/08/24 13:45:37 Error on DumpDDLs: tls: server selected unsupported protocol version 301
```
I think this is caused by old Aurora MySQL 1.x support only TLS 1.0.
(see https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraMySQL.Security.html )
For example, I could connect by mysql cli tool with `--ssl-mode=DISABLED` option.
And I cound connect to Aurora MySQL 2.x with latest mysqldef.
So I added --ssl-mode option to mysqldef.
Available values are `DISABLED, REQUIRED, PREFERRED` and default value is `PREFERRED`.
( note: I don't accept `VERIFY_CA` and `VERIFY_IDENTITY` …

[mysqldef] Add --ssl-mode option.

---

cmd/psqldef/tests.yml
database/postgres/database.go

I found a bug when dumping schema on postgresql where column comments are expanded to all tables.
It seems that the process of retrieving comments for the specified table is omitting the specification of the table.
I fixed a problem when retrieving comments by adding a `where` condition to filter by table.

Separate comment schema for each table.

---

cmd/mysqldef/mysqldef.go
database/database.go
database/mysql/database.go

We use RDS as MySQL. 
I want to add an option to specify a server certificate because I want to encrypt the connection to the DB instance with SSL/TLS.
see: https://aws.amazon.com/premiumsupport/knowledge-center/rds-connect-ssl-connection/

[mysqldef] Add ssl-ca option 

---

cmd/psqldef/psqldef_test.go
cmd/psqldef/tests.yml
database/postgres/database.go
database/postgres/parser.go
parser/ast.go
schema/ast.go
schema/generator.go
schema/parser.go

`EXTENSION` to be managed in the schema file.
New supported syntax is `CREATE EXTENSION xxx`.
Version checking for extension is not yet supported 🙏 
NOTE: In environments already using any EXTENSION, if you try to apply before adding the extension to the schema file, `DROP EXTENSION xxx` will be applied. Be sure to add `CREATE EXTENSION xxx` to the schema file before applying.

[psqldef] Introduced extension support

---

Makefile

This PR updates Makefile to append `.exe` to windows executables so that they can be executed.
Closes #293

Add .exe extension to windows executables

---

cmd/mssqldef/mssqldef_test.go
cmd/mysqldef/mysqldef_test.go
cmd/mysqldef/tests.yml
cmd/psqldef/psqldef_test.go
schema/ast.go
schema/generator.go

For the consistency between `ALTER TABLE ... DROP KEY` and `ALTER TABLE ... ADD key`, etc.

Change index types to upper case in ALTER TABLE

---

cmd/mssqldef/mssqldef.go
cmd/mysqldef/mysqldef.go
cmd/psqldef/psqldef.go
cmd/sqlite3def/sqlite3def.go
cmd/sqlite3def/sqlite3def_test.go
sqldef.go

Added option to `sqldef.Run()` to pass DDLs as a string so that sqldef can be used in single binary without specifying schema file on the filesystem.
At first I was going to use `fs.FS` (#314) , but then I decided it was unnecessary, so I created this pull request instead. See the PR  for use cases which requires this this fix and the fear that interface changes will break code compatibility.

Add DesiredDDLs option to pass DDLs as string

---

cmd/psqldef/tests.yml
database/postgres/parser.go

fixes #334 
I fixed parser for `interval` type.
If there is better way, please let me know.

psqldef: Parse interval type

---

cmd/mssqldef/tests.yml
database/mssql/database.go

fixes #337
Semicolons are inserted at ends of CREATE INDEX statement.

mssqldef: Fixed exporting error when a table has multiple indexes.

---

cmd/mssqldef/tests.yml
database/mssql/database.go

[mssqldef] Add semicolon to exported view definition.

---

cmd/mysqldef/mysqldef_test.go
schema/generator.go

Now, there is a difference between Index unspecified and USING BTREE.
fixed to set default value when comparing Indexes so that there is no difference.
* RDBMS: MySQL
* Version: -
```
id int(11) NOT NULL,
KEY index_id (id)
);
```
```
id int(11) NOT NULL,
KEY index_id (id) USING BTREE
);
```
```
ALTER TABLE `users` DROP KEY `index_id` (`id`);
ALTER TABLE `users` ADD KEY `index_id` (`id`) USING BTREE;
```
```
-- Nothing is modified --
```

MySQL's default index is B-Tree, so if not specified, the comparison is performed as B-Tree

---

Makefile

As with [build](https://github.com/k0kubun/sqldef/blob/d8b3375a13ee2106374ff81243b0f6a9e953e02f/Makefile#L26-L28), I explicitly added CGO_ENABLED=1 in test-psqldef as well

add CGO_ENABLED=1 explicitly

---

.github/workflows/sqldef.yml
cmd/psqldef/psqldef_test.go

posgtresql v15 was released, so I added to the test matrix.
https://www.postgresql.org/docs/15/release-15.html#id-1.11.6.7.4
From v15, postgres remove PUBLIC creation permission on the public schema as default.
So, I added GRANT ALL to dummy role for test.

add postgresql 15 to test matrix

---

database/postgres/parser.go
database/postgres/parser_test.go
database/postgres/tests.yml
go.mod
go.sum

In this pull request, we have improved the postgres parser tests by comparing the parsing results with those of the generic parser.
Previously, the tests only checked if the parsing process completed without errors, which made it difficult to verify if the parsing was done correctly. 
To resolve this issue, I suggest comparing the postgres parser test results with the generic parser results to ensure they are identical. However, due to the complexity of making every test case match the generic parser's results, the comparison is done only for cases with the `compare_with_generic_parser` option enabled.
To perform the struct comparisons, I used the [stretchr/testify](https://github.com/stretchr/testify) library, which provided the most desirable behavior after testing other libraries such …

Enhance postgres parser tests by comparing with generic parser results

---

cmd/psqldef/psqldef_test.go
database/postgres/database.go

There was a bug causing an error when multiple indices existed in a MATERIALIZED VIEW or when multiple MATERIALIZED VIEWs were present.
exmple
schema.sql
```sql
CREATE MATERIALIZED VIEW public.view_users AS SELECT * FROM users;
CREATE INDEX index_name on public.view_users (name);
CREATE UNIQUE INDEX index_age on public.view_users (age);
```
get ddl
```sql
CREATE MATERIALIZED VIEW public.view_users AS SELECT * FROM users;
CREATE INDEX index_name on public.view_users (name)
CREATE UNIQUE INDEX index_age on public.view_users (age)
```
The reason was the absence of a semicolon at the end of the index. This time, we have addressed the issue by adding semicolons and also added test codes.

[psqldef]Fix Error in Materialized Views with Multiple Indices

---

database/postgres/parser.go
database/postgres/tests.yml

Added support for constraint syntax to add unique index and foreign key in ALTER TABLE. The following SQL can now be parsed by the postgres parser.
```sql
ALTER TABLE users ADD CONSTRAINT username UNIQUE (name, age);
ALTER TABLE ONLY public.posts ADD CONSTRAINT posts_ibfk_1 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL ON UPDATE RESTRICT;
```

Support alter table constraint for postgres parser

---

database/postgres/parser.go

The changes on https://github.com/k0kubun/sqldef/pull/404 were not compatible with the type updated on https://github.com/k0kubun/sqldef/pull/406.

Fix errors caused by updating to pgquery v4

---

README.md
cmd/mssqldef/mssqldef.go
cmd/mysqldef/mysqldef.go
cmd/psqldef/psqldef.go
cmd/sqlite3def/sqlite3def.go

I'm sorry if I misunderstood something, but this option enables `DROP`, so `skip` isn't the correct description I think.

Fix the description of `enable-drop-table` option

---

cmd/testutils/testutils.go
database/database.go
database/mssql/parser_test.go
database/mysql/database.go
database/postgres/parser_test.go
sqldef.go

`ioutil` package is deprecated since Go 1.16.
https://pkg.go.dev/io/ioutil#pkg-overview
This fixes not to use a function of `ioutil`.

Don't use deprecated `ioutil` package

---

database/postgres/parser.go
database/postgres/tests.yml

This PR resolves the error in https://github.com/k0kubun/sqldef/issues/397. However, there is a problem as follows.
```sql
CREATE TABLE public.test_table (
"col1" numeric,
"col2" numeric
);
CREATE VIEW public.test_view AS SELECT t.* FROM test_table t;
```
```
$ go run ./cmd/psqldef -h localhost -U postgres sandbox < schema.sql
-- Apply --
CREATE TABLE public.test_table (
"col1" numeric,
"col2" numeric
);
CREATE VIEW public.test_view AS SELECT t.* FROM test_table t;
```
```
$ go run ./cmd/psqldef -h localhost -U postgres sandbox < schema.sql
-- Apply --
CREATE OR REPLACE VIEW "public"."test_view" AS select t.* from test_table as t;
```
No matter how many times `psqldef` is executed, `CREATE OR REPLACE VIEW` is executed. It seems that the cause is that when `select *` is specified, the …

Support `select *` for postgres parser

---

cmd/testutils/testutils.go
database/database.go
database/mssql/parser_test.go
database/mysql/database.go
database/postgres/parser_test.go
sqldef.go

Replaced the `ioutil` package with compatible functions as `ioutil` package is deprecated.
https://pkg.go.dev/io/ioutil
> Deprecated: As of Go 1.16, the same functionality is now provided by package [io](https://pkg.go.dev/io) or package [os](https://pkg.go.dev/os), and those implementations should be preferred in new code.

Migrate from deprecated ioutil to compatible functions

---

cmd/mysqldef/tests.yml
schema/generator.go

In the current version of sqldef, adding a column of SET type results in an ALTER TABLE statement with empty members. This PR fixes that issue.
```sql
CREATE TABLE alarm (id BIGINT PRIMARY KEY);
```
```sql
CREATE TABLE alarm (
id BIGINT PRIMARY KEY,
dayOfWeek SET('Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun') NOT NULL
);
```
```sql
ALTER TABLE `alarm` ADD COLUMN `dayOfWeek` set('Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun') NOT NULL AFTER `id`;
```
```sql
ALTER TABLE `alarm` ADD COLUMN `dayOfWeek` set NOT NULL AFTER `id`;
```

Fix missing SET type members

---

cmd/mysqldef/tests.yml
database/postgres/database.go
parser/ast.go
parser/parser.go
parser/parser.y
schema/ast.go
schema/generator.go
schema/parser.go

In the current version of sqldef, changing the column type from DATETIME to DATETIME(3) does not produce an ALTER TABLE statement. This PR fixes this comparison.
```sql
id bigint(20) PRIMARY KEY,
created_at datetime NOT NULL
);
```
```sql
id bigint(20) PRIMARY KEY,
created_at datetime(3) NOT NULL
);
```
```sql
ALTER TABLE `users` CHANGE COLUMN `created_at` `created_at` datetime(3) NOT NULL;
```
```sql
```

Add support DATETIME fractional seconds part

---

database/postgres/database.go

I salute a great tool.
https://github.com/k0kubun/sqldef/pull/130
Execution of `psqldef` failed because `sslcert` and `sslkey` were not set correctly.
```bash
$ psqldef -U username -W password -h 127.0.0.1 -p 26257 -f schema.sql sample
2023/09/18 14:44:28 Error on DumpDDLs: dial tcp 127.0.0.1:26257: connect: connection refused
```
Change to evaluate PGSSLCERT and PGSSLKEY.
This will allow sslcert and sslkey to be set.
ssl_cert: https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNECT-SSLCERT
ssl_key: https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNECT-SSLKEY
ENV and option mapping: https://www.postgresql.org/docs/current/libpq-envars.html#LIBPQ-ENVARS

psqldef: Support PGSSLCERT & PGSSLKEY

---

README.md
cmd/psqldef/psqldef.go
cmd/psqldef/psqldef_test.go
database/database.go
database/postgres/database.go

I just add `psqldef --skip-view` allong w/ #454 discussion, and confirmed this can skip parsing views including both #454 and #455 cases.
This patch mostly traces #214 implementation.
Trick or treat!

add --skip-view option to psqldef

---

README.md
cmd/psqldef/psqldef.go
cmd/psqldef/psqldef_test.go
database/database.go
database/postgres/database.go

I have added the `--skip-extension` option to psqldef because there are cases where we don't want to manage extensions with sqldef.
@k0kubun Please review. If you approve, I will merge and release it myself.

[psqldef] Add --skip-extension option

---

cmd/psqldef/tests.yml
database/postgres/parser.go
database/postgres/tests.yml

The error occurred because the generic parser doesn't support the array constructor, causing an issue with the following SQL:
```
$ cat schema.sql
CREATE TABLE foo (
arr integer[] default ARRAY[]::interger[]
);
```
```
$ psqldef -h localhost -U postgres sandbox < schema.sql
found syntax error when parsing DDL "CREATE TABLE foo (
arr integer[] default ARRAY[]::interger[]
)": syntax error at position 49 near 'array'
```
To resolve this problem, I implemented the parsing of default values in the Postgres parser. As a result, values other than the array constructor can now be parsed as well.

Support default value in postgres parser

---

database/postgres/parser.go
database/postgres/tests.yml

The error occurred because the generic parser doesn't support the unique constraint in create table, causing an issue with the following SQL:
```sql
CREATE TABLE foo (
id int,
CONSTRAINT uniq_id UNIQUE (id)
);
```
```
$ psqldef -h localhost -U postgres sandbox < schema.sql
found syntax error when parsing DDL "CREATE TABLE foo (
id int,
CONSTRAINT uniq_id UNIQUE (id)
)": syntax error at position 61 near 'unique'
```
To resolve this problem, I implemented the parsing of constraints in the Postgres parser.

Support constraint in create table for postgres parser

---

cmd/psqldef/tests.yml
database/postgres/parser.go
database/postgres/tests.yml

The error occurred because the generic parser doesn't support the type cast of date in check constraint, causing an issue with the following SQL:
```sql
CREATE TABLE test (
d date CHECK (d >= '2022-01-01'::date)
);
```
```
$ psqldef -h localhost -U postgres sandbox < .tmp/schema.sql
found syntax error when parsing DDL "CREATE TABLE test (
d date CHECK (d >= '2022-01-01'::date)
)": syntax error at position 60 near 'date'
```
To resolve this problem, I implemented the parsing of check constraint in the Postgres parser.

Support check constraint in postgres parser

---

cmd/psqldef/tests.yml
database/postgres/parser.go
database/postgres/tests.yml
parser/ast.go

Fixed an error in psqldef with SQL using `ALL`, `ANY`, and `SOME` as follows.
```sql
CREATE TABLE test (
n1 int CHECK (n1 = ANY (ARRAY[1, 2, 3])),
n2 int CHECK (n2 = ALL ('{1,2,3}'::int[])),
t1 text CHECK (t1 = SOME ('{x,y}'::text[]))
);
```

Support ALL/ANY operation in postgres parser

---

cmd/psqldef/psqldef_test.go
database/postgres/parser.go
database/postgres/tests.yml

Fixed the following error:
```sql
CREATE TYPE tags AS ENUM ('foo');
CREATE TABLE test (
tag public.tags
);
```
```
$ psqldef -h localhost -U postgres sandbox < schema.sql
found syntax error when parsing DDL "CREATE TABLE test (
tag public.tags
)": syntax error at position 36
```

[psqldef] Fix error when specifying a schema for user-defined type

---

cmd/psqldef/tests.yml
database/postgres/parser.go
database/postgres/tests.yml
parser/ast.go

Fixed type cast errors in the following cases:
```sql
create table test (
t text DEFAULT CURRENT_TIMESTAMP::date::text,
a text[] DEFAULT ARRAY[CURRENT_DATE::text]::text[],
)
```

[psqldef] Fix type cast errors

---

cmd/psqldef/tests.yml
database/postgres/database.go

We didn't support comments outside of the public schema in psqldef, so we've made adjustments to accommodate them.

psqldef: Support multiple schema for comment

---

cmd/psqldef/tests.yml
database/postgres/database.go
database/postgres/parser.go
database/postgres/tests.yml
parser/node.go
schema/ast.go
schema/generator.go
schema/parser.go

This PR contains two improvements:
1. Enable to handle adding an absent foreign key
2. Enhance `DEFERRABLE` support
```diff
id INT PRIMARY KEY
);
CREATE TABLE posts (
content TEXT,
-   user_id INT
+   user_id INT REFERENCES users(id)
);
```
**Before** (v1.7.0)
*No diff*
**After**
```sql
ALTER TABLE "public"."posts" ADD CONSTRAINT "posts_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id");
```
```diff
CREATE TABLE images (
id INT PRIMARY KEY
);
CREATE TABLE image_owners (
id INT,
type VARCHAR(20) NOT NULL,
PRIMARY KEY (type, id)
);
CREATE TABLE image_bindings (
-   image_id INT REFERENCES images(id) ON DELETE CASCADE,
+   image_id INT REFERENCES images(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
image_order INT NOT NULL,
image_owner_type …
```

[psqldef] Support absent foreign key and improve `DEFERRABLE` handling

---

cmd/psqldef/tests.yml
database/postgres/parser.go

This PR addresses bug fixes in psqldef version 0.17.1, potentially resulting from the merge of https://github.com/sqldef/sqldef/pull/497, which introduced enhancements to the parser's strictness.

psqldef: Fix some bugs in v0.17.1

---

cmd/psqldef/psqldef_test.go
cmd/psqldef/tests.yml
schema/generator.go

There was a bug that materialized view could not be dropped.
```
$ psqldef -U postgres postgres < schema.sql --export           
CREATE TABLE "public"."users" (
"id" serial NOT NULL,
"name" character varying(100) NOT NULL,
PRIMARY KEY ("id")
);
CREATE MATERIALIZED VIEW public.view_users AS SELECT id, name FROM users;
```
``` sql
create table users (
id   serial       primary key,
name varchar(100) not null
);
```
```
$ psqldef -U postgres postgres < schema.sql
-- Apply --
DROP VIEW "public"."view_users";
2024/03/26 17:52:48 pq: "view_users" is not a view
```
```
$ psqldef -U postgres postgres < schema.sql
-- Apply --
DROP MATERIALIZED VIEW "public"."view_users";
```
This was because the materialized view was recognized as a normal view. Therefore, we added a if branch for materialized …

[psqldef] Add support for dropping materialized view

---

cmd/psqldef/tests.yml
database/postgres/parser.go
database/postgres/tests.yml

I fixed the error that was occurring in this SQL.
```sql
name TEXT,
user_name TEXT
);
CREATE INDEX create_index_with_function_call ON users (name, COALESCE(user_name, 'NO_NAME'::TEXT));
```

psqldef: Fix error for index with coalesce

---

database/postgres/database.go

This PR excludes temporary tables from psqldef migration.
Having temporary tables on migration gets an ambiguous error:
```bash
2024/04/26 09:58:16 Error on DumpDDLs: sql: Scan error on column index 0, name "column_name": converting NULL to string is unsupported
```
This comes from temp tables not returning column defs.  
I think they should be excluded because we cannot say much about temporalities.
I just tried to add a test case, but couldn't find out a proper way to describe excluded DB objects. I confirmed it passes through existing tests.

Exclude a temporary table

---

README.md
cmd/mysqldef/mysqldef.go
cmd/mysqldef/mysqldef_test.go
database/database.go
schema/generator.go

Produce sql with lock option. 
Resolving https://github.com/sqldef/sqldef/issues/526 
for example, 
```
ALTER TABLE `users` ADD COLUMN `new_column` varchar(255) COLLATE utf8mb4_bin DEFAULT null AFTER `name`, LOCK=NONE;
```

[mysqldef] Add Lock option

---

cmd/psqldef/psqldef_test.go
database/database.go
database/postgres/database.go

`target_tables` allows specifying multiple tables separated by new lines, but `target_schema` could only specify a single schema. This change will allow specifying multiple schemas in target_schema as well.

Allow multiple targets for target_schema config

---

database/postgres/database.go

follow up to https://github.com/sqldef/sqldef/pull/541
```sql
create table foo.bar (id int);
create schema foo;
```
```
$ psql -h localhost -U postgres sandbox -c 'CREATE USER foo';
CREATE ROLE
$ psql -h localhost -U postgres sandbox -c 'GRANT ALL ON DATABASE sandbox TO foo';
GRANT
$ psqldef -h localhost -U foo sandbox < schema.sql
-- Apply --
create schema foo;
create table foo.bar (id int);
$ psqldef -h localhost -U foo sandbox < schema.sql
-- Apply --
create schema foo;
2024/07/13 22:31:30 pq: schema "foo" already exists
```
The reason is that for a `foo` user, the current schema becomes `foo`.
```
$ psql -h localhost -U foo sandbox -c 'select current_schema';
current_schema
----------------
foo
(1 row)
$ psql -h localhost -U postgres sandbox -c 'select current_schema';
current_schema …
```

[psqldef] Fix create schema conditions

---

cmd/psqldef/tests.yml
database/postgres/database.go
schema/generator.go
schema/generator_test.go
schema/parser.go

psqldef errors out when a comment contains an apostrophe ('). Similarly, psqldef generates invalid SQL when adding a column with a default value containing an apostrophe. Fix these by escaping apostrophes in SQL string constants.
Unrelatedly, fix incorrect format in some error handling code (schema/parser.go).

 [psqldef] Escape ' in strings

---

compose.yml

As described in [this comment](https://github.com/sqldef/sqldef/pull/560#issuecomment-2370248854), we are currently experiencing issues with MSSQL tests failing on GitHub Actions. The problem appears to be related to the MSSQL Docker image crashing on the ubuntu-latest (20.04) environment used by GitHub Actions.
To address this issue, we propose updating the MSSQL Docker image in our `compose.yml` file to:
- `mcr.microsoft.com/mssql/server:2019-CU28-ubuntu-20.04`
Additionally, we need to set `user: root` for the MSSQL service in the `compose.yml` file. This is necessary for versions 2019 and later to prevent volume mount failures.
These changes aim to resolve the MSSQL test failures on GitHub Actions.

Update MSSQL Docker image to resolve GitHub Actions crash

---

cmd/mysqldef/mysqldef_test.go
database/database.go

The previous implementation had a bug where specifying both ALGORITHM and LOCK in the configuration would result in only LOCK being applied. This PR fixes the issue to ensure both options are correctly used when specified.
```yaml
algorithm: inplace
lock: none
```
Before
```sql
ALTER TABLE `users` CHANGE COLUMN `name` `name` varchar(1000) DEFAULT NULL, LOCK=NONE;
```
After
```sql
ALTER TABLE `users` CHANGE COLUMN `name` `name` varchar(1000) DEFAULT NULL, ALGORITHM=INPLACE, LOCK=NONE;
```

[mysqldef] Fix ALGORITHM option being overwritten by LOCK in config

---

go.mod
go.sum

Related to Issue #566
With this update to go-pgquery, wazero will allocate larger memory during its initial operation, but by using a custom allocator, memory can now be allocated as needed.
Reference: https://github.com/wasilibs/go-pgquery/issues/31#issuecomment-2406412969

[psqldef] Fixed out of memory error

---

database/mssql/database.go

`sys.stats.is_incremental` only exists SQL Server 2014 (12.x) and above.
https://learn.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-stats-transact-sql?view=sql-server-ver16

mssqldef: Support legacy SQL Server versions

---

cmd/psqldef/tests.yml
database/postgres/parser.go
database/postgres/tests.yml
parser/node.go

This pull request addresses an issue where a syntax error occurs during the CREATE INDEX operation when using boolean comparisons such as `IS TRUE` . The problem was identified in the parsing process, which did not correctly handle these types of expressions.
This update specifically addresses PostgreSQL and its handling of boolean comparisons in CREATE INDEX. It is currently unclear if similar support or issues exist in other database engines like MySQL.
```
$ go test -v ./cmd/psqldef/ -run=TestApply/CreateIndexWithBoolExpr
=== RUN   TestApply
=== RUN   TestApply/CreateIndexWithBoolExpr
testutils.go:105: found syntax error when parsing DDL "CREATE INDEX create_index_with_bool ON users ((CASE WHEN is_active IS TRUE THEN 1 ELSE 0 END))": syntax error at position 48
--- FAIL: TestApply …
```

psqldef: Fix syntax error occurring when using boolean comparisons in CREATE INDEX

---

database/postgres/database.go

This fixes #594
Partition table support looks still not perfect, but I just confirmed psqldef can migrate my testing table schema created with 'PARTITION BY' clause.
I think this patch improves feasibility a little bit.
Thanks a lot for your hard work !

[psqldef] Fix missing columns and comments in partition tables

---

database/postgres/database.go

This fixes #596. And I expect it mitigates #559 slowdown, too.
`relispartition` is descirbed:
https://www.postgresql.org/docs/current/catalog-pg-class.html

[psqldef] Fix altering partitions

---

cmd/psqldef/tests.yml
schema/parser.go

Partial fix for https://github.com/sqldef/sqldef/issues/605
This PR fixes only `Issue1: COMMENT ON clause is always seen as 'change' if no schema is specified.`.
- `false positive` change is recorded at 
https://github.com/sqldef/sqldef/blob/912c9e249d3ccac4d936759a283d2c8e35a98704/schema/generator.go#L1778
- This PR  `modifies` `desired` (user specified) COMMENT clause if it didn't specify schema explicitly, so I felt this PR a bit strange approach although I've implemented. 
- paserDDL https://github.com/sqldef/sqldef/blob/912c9e249d3ccac4d936759a283d2c8e35a98704/schema/generator.go#L68 should just parse, not modify user specified DDL. But current implementation already modifies using `defaultSchema`.
- defaultSchema is introduced at …

[psqldef] Handle case when schema is not specified in COMMENT ON clause

---

cmd/psqldef/psqldef_test.go
database/postgres/database.go

[psqldef] Recognize schema for view/materializedView.
This fixes the bug that generates wrong alter statements for those when defined in a different schema.
<details>
<summary>outdated reproduction step</summary>
Creating a test in tests.yml is hard currently because it cannot set up schema outside of sqldef DDL.
"expected nothing is modified" error happens. 
And also, tests.yml doesn't support tests using a config.
So, I attached reproduction steps.
Create following three files and initialize database.
* init.sql
* config.yml
* schema.sql
init.sql
```
DROP DATABASE IF EXISTS sandbox;
CREATE DATABASE sandbox;
\c sandbox;
CREATE SCHEMA foo;
CREATE TABLE foo.users (
id BIGINT PRIMARY KEY,
name character varying(100)
);
CREATE TABLE foo.posts (
id BIGINT PRIMARY KEY,
name character …
```

[psqldef] Recognize schema for view/materializedView

---

.github/workflows/docker-build.yml

This PR adds support for multi-platform images.
It also updates the old versions used in GitHub Actions.
While you could specify a version directly if you fully trust [docker](https://github.com/docker) (which would be simpler), for consistency with the existing code we’ve continued using SHA-based version references.
[Multi\-platform image \| Docker Docs](https://docs.docker.com/build/ci/github-actions/multi-platform/)

Add multi-platform Image support

---

.github/workflows/docker-build.yml
Dockerfile
Makefile

This pull request introduces individual Docker images for each sqldef command instead of packaging multiple commands into a single image. By separating the images, each one remains lightweight and focused, which can simplify usage for those who only need a specific command.
Please review the changes, and let me know if you have any feedback or suggestions. Thank you!
This closes #661 
```
docker run --rm sqldef/mysqldef -u root -h hostname dbname --export > schema.sql
docker run -i --rm sqldef/mysqldef -u root -h hostname dbname < schema.sql
```

Add separate Docker Images for each sqldef command

---

cmd/mssqldef/mssqldef.go
cmd/mssqldef/mssqldef_test.go
cmd/mysqldef/mysqldef.go
cmd/mysqldef/mysqldef_test.go
cmd/psqldef/psqldef.go
cmd/psqldef/psqldef_test.go
cmd/sqlite3def/sqlite3def.go
cmd/sqlite3def/sqlite3def_test.go
database/database.go
sqldef.go

Discussion: https://github.com/sqldef/sqldef/discussions/677
To extend the `enable-drop-table` to `enable-drop` option.
Skip the DDL contain if `enableDrop` is true:
1. DROP TABLE
2. DROP SCHEMA
3. DROP ROLE / USER
4. DROP FUNCTION / PROCEDURE
5. DROP TRIGGER
Currently also include less dangerous DDLs: 
6. DROP VIEW
7. DROP INDEX
8. DROP SEQUENCE
9. DROP TYPE
10. DROP MATERIALIZED VIEW

feat/extend enable-drop-table to enable-drop option which block all drop ddl

---

schema/ast.go
schema/generator.go
schema/parser.go

This PR optimizes performance by replacing column lookups in []Column with a map[string]*Column, reducing the time complexity of column access from O(n) to O(1).
- Replace []Column with map[string]*Column in the Table struct.
- Adjust column ordering logic (e.g., for MySQL's AFTER) by storing columns in a separate slice for ordered iteration.
- Simplify findColumnByName to use direct map access.
- Clean up legacy functions like convertColumnsToColumnNames.

opt/Optimize column lookup with map to improve DDL diff performance

---

README.md

The content of README.md became out-of-date after https://github.com/sqldef/sqldef/pull/682 merged.
Therefore, this PR updates README.md to support the change from `enable-drop-table` to `enable-drop`

Update readme about `enable-drop`

---

cmd/mssqldef/mssqldef.go
cmd/mssqldef/mssqldef_test.go
cmd/mysqldef/mysqldef.go
cmd/mysqldef/mysqldef_test.go
cmd/psqldef/psqldef.go
cmd/psqldef/psqldef_test.go
cmd/sqlite3def/sqlite3def.go
cmd/sqlite3def/sqlite3def_test.go
cmd/testutils/testutils.go
database/file/database.go
database/mssql/database.go
database/mssql/parser.go
database/mysql/database.go
database/parser.go
database/postgres/database.go
database/postgres/parser.go
database/postgres/parser_test.go
database/sqlite3/database.go
go.mod
schema/ast.go
schema/generator.go
schema/parser.go
sqldef.go

This PR updates the module name to include the `/v2` suffix, following Go Modules versioning conventions for major version 2.
- Changed the `go.mod` module path to `github.com/sqldef/sqldef/v2`
- Updated all import paths to use `/v2`
- No functional changes; this is to ensure correct versioning and import behavior for v2 and above
Please update your import paths accordingly when upgrading to v2.

Add `/v2` suffix to module name for Go Modules v2 compatibility

---

compose.yml

refs. https://github.com/microsoft/mssql-docker/issues/895#issuecomment-2737646391
```
$ make test-mssqldef
go test -v ./cmd/mssqldef
=== RUN   TestApply
=== RUN   TestApply/TestMssqldefMultipleIndex
2025/07/05 12:40:40 TLS Handshake failed: tls: failed to parse certificate from server: x509: negative serial number
FAIL    github.com/sqldef/sqldef/v2/cmd/mssqldef        3.979s
FAIL
make: *** [Makefile:84: test-mssqldef] Error 1
```

mssqldef: Fix TLS Handshake Error of MSSQL Server.

---

cmd/psqldef/tests.yml
schema/generator.go

This PR updates the DDL generation so that **`ALTER TABLE … ADD CONSTRAINT … FOREIGN KEY` statements are emitted last**, after all other schema changes.  
It adds a new test case (`ForeignKeyConstraintsAreEmittedLast`) to confirm this behavior.
We maintain a very large schema (thousands of lines) in Git and continuously run `psqldef` to migrate our databases.  
Our style is to **write foreign keys inline in `CREATE TABLE`**, rather than as separate `ALTER TABLE` statements.
`psqldef` already supports the style of emitting standalone `ALTER TABLE ADD CONSTRAINT FOREIGN KEY` statements, as introduced in https://github.com/sqldef/sqldef/pull/500.  
This PR is a follow-up that makes the `CREATE TABLE` style easier to use in large, split schemas.
When splitting a large schema into multiple …

psqldef: Emit Foreign Key Constraints Last to Support CREATE TABLE Style (Follow‑up to #500)

---

cmd/psqldef/tests.yml
schema/generator.go

Follow-up to #500 and #705.
By this change, we no longer need to consider the place of CREATE VIEW DDLs, as they are now emitted after CREATE TABLE DDLs in the DDL generation order, similar to how foreign key constraints were resolved by #500 and #705.
This ensures that all table modifications (like adding columns) are completed before views that depend on those tables are created or modified, preventing dependency issues during schema migrations.
🔴 → 🟢

psqldef: Emit CREATE VIEW after ALTER TABLE

---

.github/workflows/sqldef.yml
schema/generator.go
schema/generator_test.go

Added newer versions of Pg, dropping obsolete Pg versions.
FYI Pg 13 to 17 are actively maintained versions, according to https://www.postgresql.org/support/versioning/
---
From Pg16, the way to normalize View definitions have been changed, which caused a test `CollateOnColumn` to fail. [a4b7607](https://github.com/sqldef/sqldef/pull/729/commits/a4b7607a983779880e1b57961f2068c63295e130) fixes the issue.
---
If the PR is okay, could you please update CI rules to drop pg 10 and 11 from required, and add pg 16 and 17 to required?

update CI targets: removed pg10, 11; added pg16, pg17

---

README.md
cmd/mssqldef/tests.yml
cmd/mysqldef/tests_tables.yml
cmd/psqldef/tests.yml
cmd/sqlite3def/tests.yml
schema/ast.go
schema/generator.go
schema/parser.go

With the similar syntax as https://github.com/sqldef/sqldef/pull/727
For example,
```sql
CREATE TABLE users ( -- @rename from=user_accounts
id bigint NOT NULL,
username text,
age integer
);
```
will create:
```sql
ALTER TABLE `user_accounts` RENAME TO `users`;
```
See for README.md and the tests for details.

Add table rename support with `@rename from=<old_table_name>` magic comments

---

.gitignore
README.md
cmd/mssqldef/mssqldef.go
cmd/mysqldef/mysqldef.go
cmd/mysqldef/mysqldef_test.go
cmd/psqldef/psqldef.go
cmd/sqlite3def/config3.yml
cmd/sqlite3def/sqlite3def.go
cmd/sqlite3def/sqlite3def_test.go
database/database.go

Discussed in https://github.com/sqldef/sqldef/discussions/716#discussioncomment-14157726
---
This PR adds the `--config-inline` flag to all sqldef tools (mysqldef, psqldef, sqlite3def, mssqldef) to allow specifying YAML configuration directly on the command line without requiring a file.
- Both `--config` and `--config-inline` can be specified multiple times
- Configs are processed in command-line order with "latter wins" semantics
- Allows flexible configuration management by mixing file-based and inline configs
```bash
mysqldef --config=base.yml --config-inline="algorithm: INSTANT" database < schema.sql
psqldef --config-inline="target_schema: public" --config-inline="skip_tables: temp_.*" database < schema.sql
```

Add `--config-inline=<yaml-string>` flag and support multiple config specifications

---

cmd/mysqldef/tests_views_triggers.yml
parser/node.go
parser/parser.go
parser/parser.y

This fixes https://github.com/sqldef/sqldef/discussions/780
When parsing triggers containing UPDATE statements without FROM clauses, the parser was incorrectly adding `FROM dual` to the UPDATE statement, which is not valid MySQL syntax and would cause execution errors.
- Modified the parser to handle empty FROM clauses properly by:
- Changing `from_opt` rule to return empty `TableExprs{}` instead of automatically adding `dual` table
- Updated `Update.Format()` to only include FROM clause when `TableExprs` is not empty using new `isEmpty()` method
- Updated `Select.Format()` to add `FROM dual` only when FROM clause is actually empty (preserving existing SELECT behavior)

allow update statements without from clause inside triggers

---

.github/workflows/sqldef.yml
.tagpr

Immutable-release is not editable. That is, once it's created, no-one uploads artifacts to that. So we need to change the release workflow to:
1. first `tagpr` creates a draft release (`release = draft`),
2. then the next workflow uploads artifacts to the draft release,
3. and finally a step in the workflow pulblishes the release.

let sqldef.yml immutable-release ready

---

.github/workflows/sqldef.yml

They are only necessary for tags.

ci: run packaging jobs only for tags

---

cmd/mssqldef/tests_fk_deps.yml
cmd/mysqldef/tests_fk_deps.yml
cmd/psqldef/tests_fk_deps.yml
schema/generator.go

Fixes an issue where changing a primary key column would fail when there are foreign keys from tables that will be dropped.

Fix foreign key recreation when dropping referencing tables

---

.github/workflows/sqldef.yml

https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#create-a-repository-dispatch-event
> The fine-grained token must have the following permission set:
>
>    "Contents" repository permissions (write)

fix permissions
